### ISSUE TITLE
Step 1: general modification

### ISSUE THREAD

**Issue by fanha99** [OCA/l10n-vietnam#5]
Base on the [Roadmap](https://docs.google.com/document/d/1r6j3_BGn4KGk4i1IC9v8-OfL80g-WJNIJ2hylnIbulo/edit#) document

## General adjustments
- [ ] Chart of account of TT200
- [ ] Chart of account hierarchy - by @minhhq09 https://github.com/OCA/account-financial-tools/pull/505
- [ ] Accounting period blocking
- [ ] Invoice Number, Form, Series needed for VAT invoice - by @fanha99 https://github.com/OCA/l10n-vietnam/pull/3
- [ ] Narration is needed for all accounting transactions
- [ ] Counterpart account

## Assets
...

## General accounting
- [ ] Evaluation of business result

## Reports
- [ ] Accounting reports
- [ ] Financial reports
- [ ] PDF reports

## HR
 - [ ] l10n_vn_hr_payroll

**Comment by fanha99** [comment]
about the account hierarchy, there is the other solution:
https://github.com/OCA/l10n-spain/pull/480

**Comment by hongquangminh** [comment]
Hi everyone,

I look around some comments in Odoo PRs. A good news is Odoo CoAs Hierarchy is back in version 11 with new model account.group. Now it merged in branch master https://github.com/odoo/odoo/pull/17367. That solution generic and better than what i did in https://github.com/OCA/account-financial-tools/pull/505. I think we should stick to the same scheme for easing the migration.

In v9 or v10. Maybe we will use the same solution like module l10n_es_account_hierarchy_report of OCA/l10n-spain and then let data only in the localization module.

**Comment by fanha99** [comment]
About the "Accounting reports", where can we find the formal template for them?

**Comment by hongquangminh** [comment]
Do you mean "Balance Sheet, Trial Balance, Cash Flow ..." base on CIRCULAR 200/2014/TT-BTC ?
