### ISSUE TITLE
[9.0] [ADD] Report Accounting Vietnamese Localization

### ISSUE THREAD

**Issue by anhvu-sg** [OCA/l10n-vietnam#9]
Hello everyone, cc @jcdrubay 

I'm Anh Vu from Trobz.
We would like to create PR _Report Accounting Vietnamese Localization_ for version 9.0 but seem this branch is not available in our repository.
Can you please help us create branch **9.0**?

About our PR, you can find [here](https://github.com/trobz/l10n-vn/pull/2) 

Many thanks
Anh Vu

**Comment by jcdrubay** [comment]
Thanks for your contribution.

The branch 9.0 is created.

I had a quick look at your repository, here are some first feedback/comments:

 - Create one PR per module
 - Split the module report_account_vas in one report_account_vas_base and one module per report (ex: report_account_vas_pl), if we don't do that it will take forever to merge and to upgrade.
 - post_function_one_time should be submitted to another repository, probably server-tols
 - some of the code from report_base_vn should be added in repository reporting_tool
 - l10n_vn_TT200: split into one module for the CoA and one module for the wizard, the module for the wizard, the wizard can be submitted to account-financial-tools as it can be used by any country to choose the main language for the Chart of Accounts.
 - report_account_vas: Why do you depend on both report_xlsx, report_xls ? I guess you should only depend on report_xlsx

**Comment by anhvu-sg** [comment]
Thanks @jcdrubay , I will check and revert
